First iteration
NatalyaAsh/sprint-five pull request #1
Opened 2024-11-25 10:57 UTC by NatalyaAsh

2024-11-25 20:32 UTC, dirtymew requested changes
Привет Наталья

отличная работа - почти все верно реализовано

есть момент который нужно исправить

2024-11-25 20:32 UTC, dirtymew commented on main.go
> +	if t.Duration.Hours() == 0 {
отлично избежала деления на 0

2024-11-25 20:32 UTC, dirtymew commented on main.go
> +	msg.TrainingType = t.TrainingType
не ошибка , но можно сразу вернуть заполненную структуру

return InfoMessage{ TrainingType: t.TrainingType , ...

2024-11-25 20:32 UTC, dirtymew commented on main.go
> +	return s.Training.TrainingInfo()
тут не по заданию 

см внимательнее
```
Для реализации этого метода для структуры Swimming{} нужно полностью переопределить TrainingInfo() с учетом того, как рассчитывается средняя скорость для плавания, дистанция и так далее. Реализация TrainingInfo() для Swimming{} будет похожа на реализацию TrainingInfo() для Training{}, но с иcпользованием методов для Swimming{}.
```

2024-11-26 08:19 UTC, NatalyaAsh commented on main.go
> +	msg.TrainingType = t.TrainingType
Исправила

2024-11-26 08:20 UTC, NatalyaAsh commented on main.go
> +	return s.Training.TrainingInfo()
Полностью переопределила метод TrainingInfo()

2024-11-26 23:57 UTC, dirtymew approved these changes
Наталья

все супер

зачет

2025-05-22 05:48 UTC, merged